### PR TITLE
Text file extensions

### PR DESCRIPTION
**Pull request by khonkhortisan**
Using .txt for text files keeps from cluttering the list of known extensions as if .WINDOWS was a filetype, and allows opening a file without having to be asked what program it should be opened with.

### CODE REVIEW

**Comment by blast007** [comment]
Just drag the files into your text editor, use File > Open, or use an editor with a sidebar file browser (such as Komodo Edit).

**Comment by khonkhortisan** [comment]
So, starting from windows explorer, navigate to where bzflag was cloned, notice a README, open notepad, File→Open, navigate to where bzflag was cloned again, then open the README.

**Comment by allejo** [comment]
A lot of developers have an editor such as Notepad++ installed, where you can right click any text file and say "Open with Notepad++". If the naming scheme would be changed, that'd move away from GNU conventions

**Comment by khonkhortisan** [comment]
Plugins already use a README format with file extension: README.CustomZoneSample.txt README.HoldTheFlag.txt README.Phoenix.txt. I left shell scripts alone, as there's no reason to run them on windows, and you can tell they're executables by font color (exec bit) and the first line. I left the irix platform alone, and doxyfile. One lowercase readme was capitalized. What was MANIFEST for?

**Comment by blast007** [comment]
The plugin readme files are end-user documentation.  The files you are suggesting to change are developer documentation.  We will not be changing them.

**Comment by khonkhortisan** [comment]
data/fonts/readme follows neither the plugin end-user documentation format README.PluginName.txt, nor the GNU convention developer documentation format README.PLATFORM.

**Pull request closed without merging**
